version: '3.6'

services:
  node:
    build:
      context: .
      target: 'dev'
      dockerfile: Dockerfile
    restart: always
    user: "node"
    stdin_open: true
    tty: true
    ports:
      - '5173:5173'
    volumes:
      - ./app:/usr/src/app